# Generated by Django 2.1.2 on 2018-11-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=50)),
                ('DT_NASC', models.DateField()),
                ('CPF', models.CharField(max_length=11)),
                ('SEXO', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=50)),
                ('DT_NASC', models.DateField()),
                ('ESPECIALIDADE', models.CharField(max_length=25)),
                ('SEXO', models.CharField(max_length=1)),
            ],
        ),
    ]
